package br.ddmsoftware.proverbiododia;

import java.lang.reflect.Field;
import java.util.Random;

/**
 * Created by douglimar on 07/09/15.
 */
public class LoadPortugueseImages {

    /*
   public int[] imagesPt = {R.drawable.abrahammaslow01, R.drawable.abrahammaslow02, R.drawable.abrahammaslow03, R.drawable.abrahammaslow04, R.drawable.abrahammaslow05, R.drawable.adamsmith01, R.drawable.adamsmith02,
            R.drawable.adamsmith03, R.drawable.adamsmith04, R.drawable.adamsmith05, R.drawable.alexander_graham_bell01, R.drawable.alexander_graham_bell02, R.drawable.alexander_graham_bell03,
            R.drawable.alexanderpope01,R.drawable.alexanderpope02, R.drawable.alexanderpope03, R.drawable.alexanderpope04, R.drawable.alexanderpope05, R.drawable.alexanderpope06, R.drawable.alexanderpope07,
            R.drawable.alexanderpope08,R.drawable.alexanderpope09, R.drawable.alexanderpope10, R.drawable.alexanderpope11, R.drawable.alexanderpope12, R.drawable.alexanderpope13, R.drawable.alexanderpope14,
            R.drawable.alexanderpope15, R.drawable.alexanderpope16, R.drawable.alexanderpope17, R.drawable.alexanderpope18,
            R.drawable.allankardec01,R.drawable.allankardec02, R.drawable.allankardec03, R.drawable.allankardec04, R.drawable.allankardec05, R.drawable.allankardec06, R.drawable.allankardec07,
            R.drawable.allankardec08,R.drawable.allankardec09,R.drawable.allankardec10,R.drawable.allankardec11,R.drawable.allankardec12,R.drawable.allankardec13,
            R.drawable.aristoteles01,R.drawable.aristoteles02,R.drawable.aristoteles03,R.drawable.aristoteles04,
            R.drawable.aristoteles05,R.drawable.aristoteles06,R.drawable.aristoteles07,R.drawable.aristoteles08,
            R.drawable.aristoteles09,R.drawable.aristoteles10,R.drawable.aristoteles11,R.drawable.aristoteles12,
            R.drawable.aristoteles13,R.drawable.aristoteles14,R.drawable.aristoteles15,R.drawable.aristoteles16,
            R.drawable.aristoteles17,R.drawable.aristoteles18,R.drawable.aristoteles19,R.drawable.aristoteles20,
            R.drawable.aristoteles21,R.drawable.aristoteles22,R.drawable.bobmarley01,R.drawable.bobmarley02,
            R.drawable.bobmarley03,R.drawable.bobmarley04,R.drawable.bobmarley05,R.drawable.bobmarley06,
            R.drawable.bobmarley07,R.drawable.bobmarley08,R.drawable.bobmarley09,R.drawable.bobmarley10,
            R.drawable.bobmarley11,R.drawable.bobmarley12,R.drawable.bobmarley13,R.drawable.bobmarley14,
            R.drawable.bobmarley15,R.drawable.bobmarley16,R.drawable.bobmarley17,R.drawable.bobmarley19,
            R.drawable.bobmarley20,R.drawable.bobmarley21,R.drawable.bobmarley22,R.drawable.bobmarley23,
            R.drawable.bobmarley24,R.drawable.bobmarley25,R.drawable.bobmarley26,R.drawable.bobmarley27,
            R.drawable.bobmarley28,R.drawable.bobmarley_18,R.drawable.cervantes01,R.drawable.cervantes02,
            R.drawable.cervantes03,R.drawable.cervantes04,R.drawable.cervantes05,R.drawable.cervantes06,
            R.drawable.cervantes07,R.drawable.cervantes08,R.drawable.cervantes09,R.drawable.cervantes10,
            R.drawable.cervantes11,R.drawable.cervantes12,R.drawable.cervantes13,R.drawable.cervantes14,
            R.drawable.cervantes15,R.drawable.cervantes16,R.drawable.cervantes17,R.drawable.cervantes18,
            R.drawable.cervantes19,R.drawable.cervantes20,R.drawable.cervantes21,R.drawable.cervantes22,
            R.drawable.cervantes23,R.drawable.cervantes24,R.drawable.cervantes25,R.drawable.cervantes26,
            R.drawable.cervantes27,R.drawable.chaplin01,R.drawable.chaplin02,R.drawable.chaplin03,
            R.drawable.chaplin04,R.drawable.chaplin05,R.drawable.chaplin06,R.drawable.chaplin07,
            R.drawable.chaplin08,R.drawable.chaplin09,R.drawable.chaplin10,R.drawable.chaplin11,
            R.drawable.chaplin12,R.drawable.chaplin13,R.drawable.chaplin14,R.drawable.chaplin15,
            R.drawable.chaplin16,R.drawable.chaplin17,R.drawable.chaplin18,R.drawable.chaplin19,
            R.drawable.chaplin20,R.drawable.chaplin21,R.drawable.chaplin22,R.drawable.chaplin23,
            R.drawable.chaplin24,R.drawable.chaplin25,R.drawable.chaplin26,R.drawable.chaplin27,
            R.drawable.chaplin28,R.drawable.chaplin29,R.drawable.chaplin30,R.drawable.churchill01,
            R.drawable.churchill02,R.drawable.churchill03,R.drawable.churchill04,R.drawable.churchill05,
            R.drawable.churchill06,R.drawable.churchill07,R.drawable.churchill08,R.drawable.churchill09,
            R.drawable.churchill10,R.drawable.churchill11,R.drawable.churchill12,R.drawable.churchill13,
            R.drawable.churchill14,R.drawable.churchill15,R.drawable.churchill16,R.drawable.churchill17,
            R.drawable.churchill18,R.drawable.churchill19,R.drawable.churchill20,R.drawable.churchill21,
            R.drawable.churchill22,R.drawable.churchill23,R.drawable.churchill24,R.drawable.churchill25,
            R.drawable.churchill26,R.drawable.claricelispector01,
            R.drawable.claricelispector02,R.drawable.claricelispector03,R.drawable.claricelispector04,R.drawable.claricelispector05,
            R.drawable.claricelispector06,R.drawable.claricelispector07,R.drawable.claricelispector08,R.drawable.claricelispector09,
            R.drawable.claricelispector10,R.drawable.claricelispector11,R.drawable.claricelispector12,R.drawable.claricelispector13,
            R.drawable.claricelispector14,R.drawable.claricelispector15,R.drawable.claricelispector16,R.drawable.claricelispector17,
            R.drawable.claricelispector18,R.drawable.confucio01,R.drawable.confucio02,R.drawable.confucio03,
            R.drawable.confucio04,R.drawable.confucio05,R.drawable.confucio06,R.drawable.confucio07,
            R.drawable.confucio08,R.drawable.confucio09,R.drawable.confucio10,R.drawable.confucio11,
            R.drawable.confucio12,R.drawable.confucio13,R.drawable.confucio14,R.drawable.confucio15,
            R.drawable.confucio16,R.drawable.confucio17,R.drawable.confucio18,R.drawable.confucio19,
            R.drawable.confucio20,R.drawable.confucio21,R.drawable.confucio22,R.drawable.confucio23,
            R.drawable.confucio24,R.drawable.confucio25,R.drawable.confucio26,R.drawable.confucio27,
            R.drawable.confucio28,R.drawable.confucio29,R.drawable.confucio30,R.drawable.confucio31,
            R.drawable.confucio32,R.drawable.confucio33,R.drawable.confucio34,R.drawable.confucio35,
            R.drawable.confucio36,R.drawable.confucio37,R.drawable.confucio38,R.drawable.confucio39,
            R.drawable.confucio40,R.drawable.confucio41,R.drawable.confucio42,R.drawable.dickens01,
            R.drawable.dickens02,R.drawable.dickens03,R.drawable.dickens04,R.drawable.dickens05,
            R.drawable.dickens06,R.drawable.dickens07,R.drawable.dickens08,R.drawable.dickens09,
            R.drawable.dickens10,R.drawable.dickens11,R.drawable.dickens12,R.drawable.dickens13,
            R.drawable.dickens14,R.drawable.dickens15,R.drawable.dickens16,R.drawable.einstein01,
            R.drawable.einstein02,R.drawable.einstein03,R.drawable.einstein04,R.drawable.einstein05,
            R.drawable.einstein06,R.drawable.einstein07,R.drawable.einstein08,R.drawable.einstein09,
            R.drawable.einstein10,R.drawable.einstein11,R.drawable.einstein12,R.drawable.einstein13,
            R.drawable.einstein14,R.drawable.einstein15,R.drawable.einstein16,R.drawable.einstein17,
            R.drawable.einstein18,R.drawable.einstein19,R.drawable.einstein20,R.drawable.einstein21,
            R.drawable.einstein22,R.drawable.einstein23,R.drawable.einstein24,R.drawable.einstein25,
            R.drawable.einstein26,R.drawable.einstein27,R.drawable.einstein28,R.drawable.einstein29,
            R.drawable.einstein30,R.drawable.fernandopessoa01,R.drawable.fernandopessoa02,R.drawable.fernandopessoa03,
            R.drawable.fernandopessoa04,R.drawable.fernandopessoa05,R.drawable.fernandopessoa06,R.drawable.fernandopessoa07,
            R.drawable.fernandopessoa08,R.drawable.fernandopessoa09,R.drawable.fernandopessoa10,R.drawable.fernandopessoa11,
            R.drawable.fernandopessoa12,R.drawable.fernandopessoa13,R.drawable.freud01,R.drawable.freud02,
            R.drawable.freud03,R.drawable.freud04,R.drawable.freud05,R.drawable.freud06,
            R.drawable.freud07,R.drawable.freud08,R.drawable.freud09,R.drawable.freud10,
            R.drawable.freud11,R.drawable.freud12,R.drawable.freud13,R.drawable.freud14,
            R.drawable.freud15,R.drawable.freud16,R.drawable.freud17,R.drawable.freud18,
            R.drawable.freud19,R.drawable.freud20,R.drawable.freud21,R.drawable.freud22,
            R.drawable.gandhi01,R.drawable.gandhi02,R.drawable.gandhi03,
            R.drawable.gandhi04,R.drawable.gandhi05,R.drawable.gandhi06,R.drawable.gandhi07,
            R.drawable.gandhi08,R.drawable.gandhi09,R.drawable.gandhi10,R.drawable.gandhi11,
            R.drawable.gandhi12,R.drawable.gandhi13,R.drawable.gandhi14,R.drawable.gandhi15,
            R.drawable.gandhi16,R.drawable.gandhi17,R.drawable.gandhi18,R.drawable.gandhi19,
            R.drawable.gandhi20,R.drawable.gandhi21,R.drawable.gandhi22,R.drawable.henryford01,
            R.drawable.henryford02,R.drawable.henryford03,R.drawable.henryford04,R.drawable.henryford05,
            R.drawable.henryford06,R.drawable.henryford07,R.drawable.henryford08,R.drawable.henryford09,
            R.drawable.henryford10,R.drawable.henryford11,R.drawable.henryford12,R.drawable.henryford13,
            R.drawable.henryford14,R.drawable.henryford15,R.drawable.henryford16,R.drawable.henryford17,
            R.drawable.henryford18,R.drawable.henryford19,R.drawable.henryford20,R.drawable.henryford21,
            R.drawable.henryford22,R.drawable.jabor01,           R.drawable.jabor02,R.drawable.jabor03,
            R.drawable.jabor04,R.drawable.jabor05,R.drawable.jabor06,R.drawable.jabor07,
            R.drawable.jabor08,R.drawable.jabor09,R.drawable.jabor10,R.drawable.jabor11,
            R.drawable.jabor12,R.drawable.jabor13,R.drawable.jabor14,R.drawable.jabor15,
            R.drawable.jabor16,R.drawable.karlmarx01,R.drawable.karlmarx02,R.drawable.karlmarx03,
            R.drawable.karlmarx04,R.drawable.karlmarx05,R.drawable.karlmarx06,R.drawable.karlmarx07,
            R.drawable.karlmarx08,R.drawable.karlmarx09,R.drawable.karlmarx10,R.drawable.karlmarx11,
            R.drawable.karlmarx12,R.drawable.karlmarx13,R.drawable.karlmarx14,R.drawable.karlmarx15,
            R.drawable.king01,R.drawable.king02,R.drawable.king03,R.drawable.king04,
            R.drawable.king05,R.drawable.king06,R.drawable.king07,R.drawable.king08,
            R.drawable.king09,R.drawable.king10,R.drawable.king11,R.drawable.king12,
            R.drawable.king13,R.drawable.king14,R.drawable.king15,R.drawable.king16,
            R.drawable.king17,R.drawable.king18,R.drawable.king19,R.drawable.king20,
            R.drawable.king21,R.drawable.malcolmx01,R.drawable.malcolmx02,R.drawable.malcolmx03,
            R.drawable.malcolmx04,R.drawable.malcolmx05,R.drawable.malcolmx06,R.drawable.malcolmx07,
            R.drawable.malcolmx08,R.drawable.malcolmx09,R.drawable.malcolmx10,R.drawable.malcolmx11,
            R.drawable.malcolmx12,R.drawable.malcolmx13,R.drawable.malcolmx14,R.drawable.malcolmx15,
            R.drawable.malcolmx16,R.drawable.mandela01,R.drawable.mandela02,R.drawable.mandela03,
            R.drawable.mandela04,R.drawable.mandela05,R.drawable.mandela06,R.drawable.mandela07,
            R.drawable.mandela08,R.drawable.mandela09,R.drawable.mandela10,R.drawable.mandela11,
            R.drawable.mandela12,R.drawable.mandela13,R.drawable.mandela14,R.drawable.mandela15,
            R.drawable.mandela16,R.drawable.mandela17,R.drawable.mandela18,R.drawable.mandela19,
            R.drawable.mandela20,R.drawable.mandela21,R.drawable.mandela22,R.drawable.mao01,
            R.drawable.mao02,R.drawable.mao03,R.drawable.mao04,R.drawable.mao05,
            R.drawable.marcusaurelius01,R.drawable.marcusaurelius02,
            R.drawable.marcusaurelius03,R.drawable.marcusaurelius04,
            R.drawable.marcusaurelius05,R.drawable.marcusaurelius06,
            R.drawable.marcusaurelius07,R.drawable.marcusaurelius08,
            R.drawable.marcusaurelius09,R.drawable.marcusaurelius10,
            R.drawable.marcusaurelius11,R.drawable.marcusaurelius12,
            R.drawable.margarethtatcher01,R.drawable.margarethtatcher02,
            R.drawable.marilynmonroe01,R.drawable.marilynmonroe02,
            R.drawable.marilynmonroe03,R.drawable.marilynmonroe04,
            R.drawable.marilynmonroe05,R.drawable.marilynmonroe06,
            R.drawable.marktwain01,R.drawable.marktwain02,
            R.drawable.marktwain03,R.drawable.marktwain04,
            R.drawable.marktwain05,R.drawable.marktwain06,
            R.drawable.marktwain07,R.drawable.marktwain08,
            R.drawable.marktwain09,R.drawable.marktwain10,
            R.drawable.marktwain11,R.drawable.marktwain12,
            R.drawable.marktwain13,R.drawable.marktwain14,
            R.drawable.marktwain15,R.drawable.marktwain16,
            R.drawable.marktwain17,R.drawable.marktwain18,
            R.drawable.marktwain19,R.drawable.marktwain20,
            R.drawable.marktwain21,R.drawable.marktwain22,
            R.drawable.marktwain23,R.drawable.marktwain24,
            R.drawable.marktwain25,R.drawable.marktwain26,
            R.drawable.marktwain27,R.drawable.marktwain28,
            R.drawable.marktwain29,R.drawable.neruda01,
            R.drawable.neruda02,R.drawable.neruda03,
            R.drawable.neruda04,R.drawable.neruda05,
            R.drawable.neruda06,R.drawable.neruda07,
            R.drawable.neruda08,R.drawable.neruda09,
            R.drawable.neruda10,R.drawable.neruda11,
            R.drawable.neruda12,R.drawable.neruda13,
            R.drawable.neruda14,R.drawable.neruda15,
            R.drawable.neruda16,R.drawable.neruda17,
            R.drawable.nietzsche01,R.drawable.nietzsche02,
            R.drawable.nietzsche03,R.drawable.nietzsche04,
            R.drawable.nietzsche05,R.drawable.nietzsche06,
            R.drawable.nietzsche07,R.drawable.nietzsche08,
            R.drawable.nietzsche09,R.drawable.nietzsche10,
            R.drawable.nietzsche11,R.drawable.nietzsche12,
            R.drawable.nietzsche13,R.drawable.nietzsche14,
            R.drawable.nietzsche15,R.drawable.nietzsche16,
            R.drawable.nietzsche17,R.drawable.nietzsche18,
            R.drawable.nietzsche19,R.drawable.nietzsche20,
            R.drawable.nietzsche21,R.drawable.nietzsche22,
            R.drawable.nietzsche23,R.drawable.nietzsche24,
            R.drawable.nietzsche25,R.drawable.nietzsche26,
            R.drawable.nietzsche27,R.drawable.nietzsche28,
            R.drawable.nietzsche29,R.drawable.nietzsche30,
            R.drawable.nietzsche31,R.drawable.oscarwilde01,
            R.drawable.oscarwilde02,
            R.drawable.oscarwilde03,
            R.drawable.oscarwilde04,
            R.drawable.oscarwilde05,
            R.drawable.oscarwilde06,
            R.drawable.oscarwilde07,
            R.drawable.oscarwilde08,
            R.drawable.oscarwilde09,
            R.drawable.oscarwilde10,
            R.drawable.oscarwilde11,
            R.drawable.oscarwilde12,
            R.drawable.oscarwilde13,
            R.drawable.oscarwilde14,
            R.drawable.oscarwilde15,
            R.drawable.oscarwilde16,
            R.drawable.oscarwilde17,
            R.drawable.oscarwilde18,
            R.drawable.oscarwilde19,
            R.drawable.oscarwilde20,
            R.drawable.oscarwilde21,
            R.drawable.oscarwilde22,
            R.drawable.oscarwilde23,
            R.drawable.oscarwilde24,
            R.drawable.oscarwilde25,
            R.drawable.oscarwilde26,
            R.drawable.oscarwilde27,
            R.drawable.oscarwilde28,
            R.drawable.oscarwilde29,
            R.drawable.oscarwilde30,
            R.drawable.oscarwilde31,
            R.drawable.paulocoelho01,
            R.drawable.paulocoelho02,
            R.drawable.paulocoelho03,
            R.drawable.paulocoelho04,
            R.drawable.paulocoelho05,
            R.drawable.paulocoelho06,
            R.drawable.paulocoelho07,
            R.drawable.paulocoelho08,
            R.drawable.paulocoelho09,
            R.drawable.paulocoelho10,
            R.drawable.paulocoelho11,
            R.drawable.paulocoelho12,
            R.drawable.paulocoelho13,
            R.drawable.paulocoelho14,
            R.drawable.paulocoelho15,
            R.drawable.paulocoelho16,
            R.drawable.paulocoelho17,
            R.drawable.paulocoelho18,
            R.drawable.paulocoelho19,
            R.drawable.paulocoelho20,
            R.drawable.paulocoelho21,
            R.drawable.paulocoelho22,
            R.drawable.paulocoelho23,
            R.drawable.paulocoelho24,
            R.drawable.paulocoelho25,
            R.drawable.paulocoelho26,
            R.drawable.peterdruker01,
            R.drawable.peterdruker02,
            R.drawable.peterdruker03,
            R.drawable.peterdruker04,
            R.drawable.peterdruker05,
            R.drawable.peterdruker06,
            R.drawable.peterdruker07,
            R.drawable.peterdruker08,
            R.drawable.peterdruker09,
            R.drawable.peterdruker10,
            R.drawable.peterdruker11,
            R.drawable.peterdruker12,
            R.drawable.peterdruker13,
            R.drawable.peterdruker14,
            R.drawable.peterdruker15,
            R.drawable.peterdruker16,
            R.drawable.peterdruker17,
            R.drawable.pitagoras01,
            R.drawable.pitagoras02,
            R.drawable.pitagoras03,
            R.drawable.pitagoras04,
            R.drawable.pitagoras05,
            R.drawable.pitagoras06,
            R.drawable.pitagoras07,
            R.drawable.pitagoras08,
            R.drawable.pitagoras09,
            R.drawable.pitagoras10,
            R.drawable.pitagoras11,
            R.drawable.pitagoras12,
            R.drawable.pitagoras13,
            R.drawable.pitagoras14,
            R.drawable.pitagoras15,
            R.drawable.pitagoras16,
            R.drawable.pitagoras17,
            R.drawable.pitagoras18,
            R.drawable.platao01,
            R.drawable.platao02,
            R.drawable.platao03,
            R.drawable.platao04,
            R.drawable.platao05,
            R.drawable.platao06,
            R.drawable.platao07,
            R.drawable.platao08,
            R.drawable.platao09,
            R.drawable.platao10,
            R.drawable.platao11,
            R.drawable.platao12,
            R.drawable.platao13,
            R.drawable.platao14,
            R.drawable.platao15,
            R.drawable.platao16,
            R.drawable.platao17,
            R.drawable.platao18,
            R.drawable.platao19,
            R.drawable.platao20,
            R.drawable.platao21,
            R.drawable.platao22,
            R.drawable.platao23,
            R.drawable.platao24,
            R.drawable.platao25,
            R.drawable.platao26,
            R.drawable.platao27,
            R.drawable.platao28,
            R.drawable.platao29,
            R.drawable.rodin01,
            R.drawable.rodin02,
            R.drawable.rodin03,
            R.drawable.rodin04,
            R.drawable.rodin05,
            R.drawable.rodin06,
            R.drawable.rodin07,
            R.drawable.rodin08,
            R.drawable.rodin09,
            R.drawable.rodin10,
            R.drawable.saintexupery01,
            R.drawable.saintexupery02,
            R.drawable.saintexupery03,
            R.drawable.saintexupery04,
            R.drawable.saintexupery05,
            R.drawable.saintexupery06,
            R.drawable.saintexupery07,
            R.drawable.saintexupery08,
            R.drawable.saintexupery09,
            R.drawable.salvadordali01,
            R.drawable.salvadordali02,
            R.drawable.salvadordali03,
            R.drawable.salvadordali04,
            R.drawable.salvadordali05,
            R.drawable.salvadordali06,
            R.drawable.salvadordali07,
            R.drawable.salvadordali08,
            R.drawable.salvadordali09,
            R.drawable.salvadordali10,
            R.drawable.schopenhauer01,
            R.drawable.schopenhauer02,
            R.drawable.schopenhauer03,
            R.drawable.schopenhauer04,
            R.drawable.schopenhauer05,
            R.drawable.schopenhauer06,
            R.drawable.shakespeare01,
            R.drawable.shakespeare02,
            R.drawable.shakespeare03,
            R.drawable.shakespeare04,
            R.drawable.shakespeare05,
            R.drawable.shakespeare06,
            R.drawable.shakespeare07,
            R.drawable.shakespeare08,
            R.drawable.shakespeare09,
            R.drawable.shakespeare10,
            R.drawable.shakespeare11,
            R.drawable.shakespeare12,
            R.drawable.shakespeare13,
            R.drawable.shakespeare14,
            R.drawable.shakespeare15,
            R.drawable.shakespeare16,
           R.drawable.shakespeare17,
            R.drawable.shakespeare18,
            R.drawable.shakespeare19,
            R.drawable.shakespeare20,
            R.drawable.shakespeare21,
            R.drawable.shakespeare22,
            R.drawable.shakespeare23,
            R.drawable.shakespeare24,
            R.drawable.shakespeare25,
            R.drawable.shakespeare26,
            R.drawable.stevejobs01,
            R.drawable.stevejobs02,
            R.drawable.stevejobs03,
            R.drawable.stevejobs04,
            R.drawable.stevejobs05,
            R.drawable.stevejobs06,
            R.drawable.stevejobs07,
            R.drawable.stevejobs08,
            R.drawable.stevejobs09,
            R.drawable.stevejobs10
            R.drawable.stevejobs11,
            R.drawable.stevejobs12,
            R.drawable.stevejobs13,
            R.drawable.stevejobs14,
            R.drawable.stevejobs15,
            R.drawable.stevejobs16,
            R.drawable.stevejobs17,
            R.drawable.stevejobs18,
            R.drawable.stevejobs19,
            R.drawable.stevejobs20,
            R.drawable.stevejobs21,
            R.drawable.stevejobs22,
            R.drawable.stevejobs23,
            R.drawable.stevejobs24,
            R.drawable.stevejobs25,
            R.drawable.stevejobs26,
            R.drawable.stevejobs27,
            R.drawable.suntzu01,
            R.drawable.suntzu02,
            R.drawable.suntzu03,
            R.drawable.suntzu04,
            R.drawable.suntzu05,
            R.drawable.suntzu06,
            R.drawable.suntzu07,
            R.drawable.suntzu08,
            R.drawable.suntzu09,
            R.drawable.suntzu10,
            R.drawable.suntzu11,
            R.drawable.suntzu12,
            R.drawable.suntzu13,
            R.drawable.suntzu14,
            R.drawable.suntzu15,
            R.drawable.suntzu16,
            R.drawable.suntzu17,
            R.drawable.suntzu18,
            R.drawable.suntzu19,
            R.drawable.suntzu20,
            R.drawable.suntzu21,
            R.drawable.suntzu22,
            R.drawable.suntzu23,
            R.drawable.suntzu24,
            R.drawable.suntzu25,
            R.drawable.suntzu26,
            R.drawable.suntzu27,
            R.drawable.suntzu28,
            R.drawable.suntzu29,
            R.drawable.suntzu30,
            R.drawable.suntzu31,
            R.drawable.suntzu32,
            R.drawable.voltaire01,
            R.drawable.voltaire02,
            R.drawable.voltaire03,
            R.drawable.voltaire04,
            R.drawable.voltaire05,
            R.drawable.voltaire06,
            R.drawable.voltaire07,
            R.drawable.voltaire08,
            R.drawable.voltaire09,
            R.drawable.voltaire10,
            R.drawable.voltaire11,
            R.drawable.voltaire12,
            R.drawable.voltaire13,
            R.drawable.voltaire14,
            R.drawable.voltaire15};
*/

    public int[] imagesPt = { R.drawable.abrahammaslow02, R.drawable.abrahammaslow05, R.drawable.adamsmith01, R.drawable.adamsmith02,
            R.drawable.adamsmith03, R.drawable.adamsmith04, R.drawable.adamsmith05,
            R.drawable.alexanderpope01,R.drawable.alexanderpope03, R.drawable.alexanderpope06, R.drawable.alexanderpope07,
            R.drawable.alexanderpope08,R.drawable.alexanderpope09, R.drawable.alexanderpope10, R.drawable.alexanderpope11, R.drawable.alexanderpope12, R.drawable.alexanderpope13, R.drawable.alexanderpope14,
            R.drawable.alexanderpope15, R.drawable.alexanderpope16, R.drawable.alexanderpope17, R.drawable.alexanderpope18,
            R.drawable.allankardec01,R.drawable.allankardec02, R.drawable.allankardec03, R.drawable.allankardec04, R.drawable.allankardec05, R.drawable.allankardec06, R.drawable.allankardec07,
            R.drawable.allankardec08,R.drawable.allankardec09,R.drawable.allankardec10,R.drawable.allankardec11,R.drawable.allankardec12,R.drawable.allankardec13,
            R.drawable.aristoteles01,R.drawable.aristoteles02,R.drawable.aristoteles03,R.drawable.aristoteles04,
            R.drawable.aristoteles09,R.drawable.aristoteles10,R.drawable.aristoteles11,R.drawable.aristoteles12,
            R.drawable.aristoteles05,R.drawable.aristoteles06,R.drawable.aristoteles07,R.drawable.aristoteles08,
            R.drawable.aristoteles13,R.drawable.aristoteles14,R.drawable.aristoteles15,R.drawable.aristoteles16,
            R.drawable.aristoteles17,R.drawable.aristoteles18,R.drawable.aristoteles19,R.drawable.aristoteles20,
            R.drawable.aristoteles21,R.drawable.aristoteles22,R.drawable.bobmarley01,R.drawable.bobmarley02,
            R.drawable.bobmarley03,R.drawable.bobmarley04,R.drawable.bobmarley05,R.drawable.bobmarley06,
            R.drawable.bobmarley07,R.drawable.bobmarley08,R.drawable.bobmarley09,R.drawable.bobmarley10,
            R.drawable.bobmarley12,R.drawable.bobmarley13,R.drawable.bobmarley14,
            R.drawable.bobmarley15,R.drawable.bobmarley16,R.drawable.bobmarley17,R.drawable.bobmarley19,
            R.drawable.bobmarley20, R.drawable.bobmarley21,R.drawable.bobmarley22,R.drawable.bobmarley23,
            R.drawable.bobmarley24,R.drawable.bobmarley25,
            R.drawable.bobmarley28,R.drawable.bobmarley_18,R.drawable.cervantes01,R.drawable.cervantes02,
            R.drawable.cervantes03,R.drawable.cervantes04,R.drawable.cervantes05,R.drawable.cervantes06,
            R.drawable.cervantes07,R.drawable.cervantes08,R.drawable.cervantes09,R.drawable.cervantes10,
            R.drawable.cervantes12,R.drawable.cervantes13,R.drawable.cervantes14,
            R.drawable.cervantes15,R.drawable.cervantes16,R.drawable.cervantes17,R.drawable.cervantes18,
            R.drawable.cervantes19,R.drawable.cervantes20,R.drawable.cervantes21,R.drawable.cervantes22,
            R.drawable.cervantes23,R.drawable.cervantes24,R.drawable.cervantes25,R.drawable.cervantes27,R.drawable.chaplin01,R.drawable.chaplin02,R.drawable.chaplin03,
            R.drawable.chaplin04,R.drawable.chaplin05,R.drawable.chaplin06,R.drawable.chaplin07,
            R.drawable.chaplin08,R.drawable.chaplin09,R.drawable.chaplin10,
            R.drawable.chaplin12,R.drawable.chaplin13,R.drawable.chaplin14,
            R.drawable.chaplin16,R.drawable.chaplin17,R.drawable.chaplin19,
            R.drawable.chaplin20,R.drawable.chaplin21,R.drawable.chaplin22,R.drawable.chaplin23,
            R.drawable.chaplin24,R.drawable.chaplin25,R.drawable.chaplin26,R.drawable.chaplin27,
            R.drawable.chaplin28,R.drawable.chaplin30,R.drawable.churchill01,
            R.drawable.churchill02,R.drawable.churchill04,R.drawable.churchill05, R.drawable.churchill06,R.drawable.churchill07,R.drawable.churchill08,R.drawable.churchill09,
            R.drawable.churchill11,R.drawable.churchill12,R.drawable.churchill13,R.drawable.churchill14,R.drawable.churchill15,R.drawable.churchill16,R.drawable.churchill17,
            R.drawable.churchill18,R.drawable.churchill19,R.drawable.churchill20,R.drawable.churchill21,R.drawable.churchill23,R.drawable.churchill24,R.drawable.churchill25,
            R.drawable.churchill26,R.drawable.claricelispector01,R.drawable.claricelispector02,R.drawable.claricelispector03,
            R.drawable.claricelispector05, R.drawable.claricelispector06,R.drawable.claricelispector07,R.drawable.claricelispector08,R.drawable.claricelispector09,
            R.drawable.claricelispector10,R.drawable.claricelispector11,R.drawable.claricelispector12,R.drawable.claricelispector13,
            R.drawable.claricelispector14,R.drawable.claricelispector15,R.drawable.claricelispector16,R.drawable.claricelispector17, R.drawable.claricelispector18,
            R.drawable.confucio01,R.drawable.confucio03,R.drawable.confucio04,R.drawable.confucio06,R.drawable.confucio07,
            R.drawable.confucio08,R.drawable.confucio09,R.drawable.confucio11,R.drawable.confucio12,R.drawable.confucio13,
            R.drawable.confucio14,R.drawable.confucio15,R.drawable.confucio16,R.drawable.confucio18,
            R.drawable.confucio21,R.drawable.confucio22,R.drawable.confucio23,R.drawable.confucio24,R.drawable.confucio25,
            R.drawable.confucio26,R.drawable.confucio27,R.drawable.confucio28,R.drawable.confucio31,
            R.drawable.confucio32,R.drawable.confucio34,R.drawable.confucio35,R.drawable.confucio37,R.drawable.confucio38,R.drawable.confucio40,R.drawable.confucio41,
            R.drawable.dickens02,R.drawable.dickens03,R.drawable.dickens04,R.drawable.dickens05, R.drawable.dickens06,R.drawable.dickens07,
            R.drawable.dickens08,R.drawable.dickens09, R.drawable.dickens10,R.drawable.dickens11,R.drawable.dickens12,R.drawable.dickens13, R.drawable.dickens14,R.drawable.dickens15,R.drawable.dickens16,
            R.drawable.einstein01, R.drawable.einstein02, R.drawable.einstein03,R.drawable.einstein04,R.drawable.einstein05,R.drawable.einstein06, R.drawable.einstein07,
            R.drawable.einstein08,R.drawable.einstein09,R.drawable.einstein10, R.drawable.einstein11, R.drawable.einstein12, R.drawable.einstein13, R.drawable.einstein14,
            R.drawable.einstein16, R.drawable.einstein17, R.drawable.einstein18, R.drawable.einstein20, R.drawable.einstein21, R.drawable.einstein22, R.drawable.einstein23,
            R.drawable.einstein25, R.drawable.einstein27, R.drawable.einstein28, R.drawable.einstein30,
            R.drawable.fernandopessoa01,R.drawable.fernandopessoa02,R.drawable.fernandopessoa03,
            R.drawable.fernandopessoa04,R.drawable.fernandopessoa05,R.drawable.fernandopessoa06,R.drawable.fernandopessoa07,
            R.drawable.fernandopessoa08,R.drawable.fernandopessoa09,R.drawable.fernandopessoa10,R.drawable.fernandopessoa11,
            R.drawable.fernandopessoa12,R.drawable.fernandopessoa13,R.drawable.freud01,R.drawable.freud02,
            R.drawable.freud03,R.drawable.freud04,R.drawable.freud05,R.drawable.freud06,
            R.drawable.freud07,R.drawable.freud08,R.drawable.freud10,
            R.drawable.freud11,R.drawable.freud12,R.drawable.freud13,R.drawable.freud14,R.drawable.freud17,R.drawable.freud18,
            R.drawable.freud19,R.drawable.freud20,R.drawable.freud21,R.drawable.freud22,
            R.drawable.gandhi01,R.drawable.gandhi02,R.drawable.gandhi03,
            R.drawable.gandhi04,R.drawable.gandhi05,R.drawable.gandhi06,R.drawable.gandhi07,
            R.drawable.gandhi08,R.drawable.gandhi09,R.drawable.gandhi10,R.drawable.gandhi11,
            R.drawable.gandhi12,R.drawable.gandhi13,R.drawable.gandhi14,R.drawable.gandhi15,
            R.drawable.gandhi16,R.drawable.gandhi17,R.drawable.gandhi18,R.drawable.gandhi19,
            R.drawable.gandhi20,R.drawable.gandhi21,R.drawable.gandhi22,R.drawable.henryford01,
            R.drawable.henryford03,R.drawable.henryford04,R.drawable.henryford05,
            R.drawable.henryford06,R.drawable.henryford07,R.drawable.henryford08,R.drawable.henryford09,
            R.drawable.henryford10,R.drawable.henryford11,R.drawable.henryford12,R.drawable.henryford13,
            R.drawable.henryford14,R.drawable.henryford15,R.drawable.henryford16,
            R.drawable.henryford18,R.drawable.henryford19,R.drawable.henryford20,R.drawable.henryford21,
            R.drawable.henryford22,R.drawable.jabor01,           R.drawable.jabor02,R.drawable.jabor03,
            R.drawable.jabor04,R.drawable.jabor05,R.drawable.jabor06,R.drawable.jabor07,
            R.drawable.jabor08,R.drawable.jabor09,R.drawable.jabor10,R.drawable.jabor11,
            R.drawable.jabor12,R.drawable.jabor13,R.drawable.jabor14,R.drawable.jabor15,
            R.drawable.jabor16,R.drawable.karlmarx01,R.drawable.karlmarx02,
            R.drawable.karlmarx04,R.drawable.karlmarx06,R.drawable.karlmarx07,
            R.drawable.karlmarx08,R.drawable.karlmarx09,R.drawable.karlmarx10,R.drawable.karlmarx11,
            R.drawable.karlmarx12,R.drawable.karlmarx13,R.drawable.karlmarx14,
            R.drawable.king01,R.drawable.king02,R.drawable.king03,R.drawable.king04,
            R.drawable.king05,R.drawable.king06,R.drawable.king07,R.drawable.king08,
            R.drawable.king09,R.drawable.king10,R.drawable.king11,R.drawable.king12,
            R.drawable.king13,R.drawable.king14,R.drawable.king15,R.drawable.king16,
            R.drawable.king17,R.drawable.king18,R.drawable.king19,R.drawable.king20,
            R.drawable.king21,R.drawable.malcolmx01,R.drawable.malcolmx02,R.drawable.malcolmx03,
            R.drawable.malcolmx04,R.drawable.malcolmx05,R.drawable.malcolmx06,R.drawable.malcolmx07,
            R.drawable.malcolmx08,R.drawable.malcolmx09,R.drawable.malcolmx10,R.drawable.malcolmx11,
            R.drawable.malcolmx12,R.drawable.malcolmx13,R.drawable.malcolmx14,R.drawable.malcolmx15,
            R.drawable.malcolmx16,R.drawable.mandela01,R.drawable.mandela02,R.drawable.mandela03,
            R.drawable.mandela04,R.drawable.mandela05,R.drawable.mandela06,R.drawable.mandela07,
            R.drawable.mandela08,R.drawable.mandela09,R.drawable.mandela10,R.drawable.mandela11,
            R.drawable.mandela12,R.drawable.mandela13,R.drawable.mandela14,R.drawable.mandela15,
            R.drawable.mandela16,R.drawable.mandela17,R.drawable.mandela18,R.drawable.mandela19,
            R.drawable.mandela20,R.drawable.mandela21,R.drawable.mandela22,R.drawable.mao01,
            R.drawable.mao02,R.drawable.mao03,R.drawable.mao04,R.drawable.mao05,
            R.drawable.marcusaurelius01,R.drawable.marcusaurelius02, R.drawable.marcusaurelius03,R.drawable.marcusaurelius04, R.drawable.marcusaurelius05,R.drawable.marcusaurelius06, R.drawable.marcusaurelius07,R.drawable.marcusaurelius08, R.drawable.marcusaurelius09,R.drawable.marcusaurelius10,
            R.drawable.marcusaurelius11,R.drawable.marcusaurelius12,
            R.drawable.margarethtatcher01,R.drawable.margarethtatcher02,
            R.drawable.marilynmonroe01,R.drawable.marilynmonroe02, R.drawable.marilynmonroe03,R.drawable.marilynmonroe04, R.drawable.marilynmonroe05,R.drawable.marilynmonroe06,
            R.drawable.marktwain01,R.drawable.marktwain02, R.drawable.marktwain03,R.drawable.marktwain04, R.drawable.marktwain05,R.drawable.marktwain06, R.drawable.marktwain07,R.drawable.marktwain08, R.drawable.marktwain09,R.drawable.marktwain10, R.drawable.marktwain11,R.drawable.marktwain12, R.drawable.marktwain13,R.drawable.marktwain14, R.drawable.marktwain15,R.drawable.marktwain16, R.drawable.marktwain17,R.drawable.marktwain18, R.drawable.marktwain19,R.drawable.marktwain20, R.drawable.marktwain21,R.drawable.marktwain22, R.drawable.marktwain23,R.drawable.marktwain24, R.drawable.marktwain25,R.drawable.marktwain26, R.drawable.marktwain27,R.drawable.marktwain28,
            R.drawable.marktwain29,R.drawable.neruda01, R.drawable.neruda02,R.drawable.neruda03, R.drawable.neruda04,R.drawable.neruda05, R.drawable.neruda06,R.drawable.neruda07, R.drawable.neruda08,R.drawable.neruda09, R.drawable.neruda10,R.drawable.neruda11, R.drawable.neruda12,R.drawable.neruda13, R.drawable.neruda14,R.drawable.neruda15, R.drawable.neruda16,R.drawable.neruda17,
            R.drawable.nietzsche01,R.drawable.nietzsche02, R.drawable.nietzsche03,R.drawable.nietzsche04, R.drawable.nietzsche05,R.drawable.nietzsche06, R.drawable.nietzsche07,R.drawable.nietzsche08, R.drawable.nietzsche09,R.drawable.nietzsche10, R.drawable.nietzsche11,R.drawable.nietzsche12, R.drawable.nietzsche13,R.drawable.nietzsche14, R.drawable.nietzsche15,R.drawable.nietzsche16, R.drawable.nietzsche17,R.drawable.nietzsche18, R.drawable.nietzsche19,R.drawable.nietzsche20, R.drawable.nietzsche21,R.drawable.nietzsche22, R.drawable.nietzsche23,R.drawable.nietzsche24, R.drawable.nietzsche25,R.drawable.nietzsche26, R.drawable.nietzsche27,R.drawable.nietzsche28, R.drawable.nietzsche29,R.drawable.nietzsche30, R.drawable.nietzsche31,
            R.drawable.oscarwilde01, R.drawable.oscarwilde02, R.drawable.oscarwilde03, R.drawable.oscarwilde04, R.drawable.oscarwilde05, R.drawable.oscarwilde06,  R.drawable.oscarwilde08, R.drawable.oscarwilde09, R.drawable.oscarwilde10, R.drawable.oscarwilde11, R.drawable.oscarwilde12, R.drawable.oscarwilde13, R.drawable.oscarwilde14, R.drawable.oscarwilde15, R.drawable.oscarwilde16, R.drawable.oscarwilde17, R.drawable.oscarwilde18, R.drawable.oscarwilde19, R.drawable.oscarwilde20, R.drawable.oscarwilde21, R.drawable.oscarwilde22, R.drawable.oscarwilde23, R.drawable.oscarwilde24, R.drawable.oscarwilde25, R.drawable.oscarwilde26, R.drawable.oscarwilde27, R.drawable.oscarwilde28, R.drawable.oscarwilde29, R.drawable.oscarwilde30, R.drawable.oscarwilde31,
            R.drawable.paulocoelho01, R.drawable.paulocoelho02, R.drawable.paulocoelho03, R.drawable.paulocoelho04, R.drawable.paulocoelho05, R.drawable.paulocoelho06, R.drawable.paulocoelho07, R.drawable.paulocoelho08, R.drawable.paulocoelho09, R.drawable.paulocoelho10, R.drawable.paulocoelho11, R.drawable.paulocoelho12, R.drawable.paulocoelho13, R.drawable.paulocoelho14, R.drawable.paulocoelho15, R.drawable.paulocoelho16, R.drawable.paulocoelho17, R.drawable.paulocoelho18, R.drawable.paulocoelho19, R.drawable.paulocoelho20, R.drawable.paulocoelho21, R.drawable.paulocoelho22, R.drawable.paulocoelho23, R.drawable.paulocoelho24, R.drawable.paulocoelho25, R.drawable.paulocoelho26,
            R.drawable.peterdruker01, R.drawable.peterdruker02, R.drawable.peterdruker03, R.drawable.peterdruker04, R.drawable.peterdruker05, R.drawable.peterdruker06, R.drawable.peterdruker07, R.drawable.peterdruker08, R.drawable.peterdruker09, R.drawable.peterdruker10, R.drawable.peterdruker11, R.drawable.peterdruker12, R.drawable.peterdruker13, R.drawable.peterdruker14, R.drawable.peterdruker15, R.drawable.peterdruker16, R.drawable.peterdruker17,
            R.drawable.pitagoras01, R.drawable.pitagoras02, R.drawable.pitagoras03, R.drawable.pitagoras04, R.drawable.pitagoras05, R.drawable.pitagoras06, R.drawable.pitagoras07, R.drawable.pitagoras08, R.drawable.pitagoras09, R.drawable.pitagoras10, R.drawable.pitagoras11, R.drawable.pitagoras12, R.drawable.pitagoras13, R.drawable.pitagoras14, R.drawable.pitagoras15, R.drawable.pitagoras16, R.drawable.pitagoras17, R.drawable.pitagoras18,
            R.drawable.platao01, R.drawable.platao02, R.drawable.platao03, R.drawable.platao04, R.drawable.platao05, R.drawable.platao06, R.drawable.platao07, R.drawable.platao08, R.drawable.platao09, R.drawable.platao10, R.drawable.platao11, R.drawable.platao12, R.drawable.platao13, R.drawable.platao14, R.drawable.platao15, R.drawable.platao16, R.drawable.platao17, R.drawable.platao18, R.drawable.platao19, R.drawable.platao20, R.drawable.platao21, R.drawable.platao22, R.drawable.platao23, R.drawable.platao24, R.drawable.platao25, R.drawable.platao26, R.drawable.platao27, R.drawable.platao28, R.drawable.platao29, R.drawable.rodin01, R.drawable.rodin02, R.drawable.rodin03, R.drawable.rodin04, R.drawable.rodin05, R.drawable.rodin06, R.drawable.rodin07, R.drawable.rodin08, R.drawable.rodin09, R.drawable.rodin10, R.drawable.saintexupery01, R.drawable.saintexupery02, R.drawable.saintexupery03, R.drawable.saintexupery04, R.drawable.saintexupery05, R.drawable.saintexupery06, R.drawable.saintexupery07, R.drawable.saintexupery08, R.drawable.saintexupery09, R.drawable.salvadordali01, R.drawable.salvadordali02, R.drawable.salvadordali03, R.drawable.salvadordali04, R.drawable.salvadordali05, R.drawable.salvadordali06, R.drawable.salvadordali07, R.drawable.salvadordali08, R.drawable.salvadordali09, R.drawable.salvadordali10, R.drawable.schopenhauer01, R.drawable.schopenhauer02, R.drawable.schopenhauer03, R.drawable.schopenhauer04, R.drawable.schopenhauer05, R.drawable.schopenhauer06, R.drawable.shakespeare01, R.drawable.shakespeare02, R.drawable.shakespeare03, R.drawable.shakespeare04, R.drawable.shakespeare05, R.drawable.shakespeare06, R.drawable.shakespeare07, R.drawable.shakespeare08, R.drawable.shakespeare09, R.drawable.shakespeare10, R.drawable.shakespeare11, R.drawable.shakespeare12, R.drawable.shakespeare13, R.drawable.shakespeare14, R.drawable.shakespeare15, R.drawable.shakespeare16, R.drawable.shakespeare17, R.drawable.shakespeare18, R.drawable.shakespeare19, R.drawable.shakespeare20, R.drawable.shakespeare21, R.drawable.shakespeare22, R.drawable.shakespeare23, R.drawable.shakespeare24, R.drawable.shakespeare25, R.drawable.shakespeare26,
            R.drawable.stevejobs01, R.drawable.stevejobs02, R.drawable.stevejobs03, R.drawable.stevejobs04, R.drawable.stevejobs05, R.drawable.stevejobs06, R.drawable.stevejobs07, R.drawable.stevejobs08, R.drawable.stevejobs09, R.drawable.stevejobs10, R.drawable.stevejobs11, R.drawable.stevejobs12, R.drawable.stevejobs13, R.drawable.stevejobs14, R.drawable.stevejobs15, R.drawable.stevejobs16, R.drawable.stevejobs17, R.drawable.stevejobs18, R.drawable.stevejobs19, R.drawable.stevejobs20, R.drawable.stevejobs21, R.drawable.stevejobs22, R.drawable.stevejobs23, R.drawable.stevejobs24, R.drawable.stevejobs25, R.drawable.stevejobs26,
            R.drawable.stevejobs27, R.drawable.suntzu01, R.drawable.suntzu02, R.drawable.suntzu03, R.drawable.suntzu04, R.drawable.suntzu05, R.drawable.suntzu06, R.drawable.suntzu07, R.drawable.suntzu08, R.drawable.suntzu09, R.drawable.suntzu10, R.drawable.suntzu11, R.drawable.suntzu12, R.drawable.suntzu13, R.drawable.suntzu14, R.drawable.suntzu15, R.drawable.suntzu16, R.drawable.suntzu17, R.drawable.suntzu18, R.drawable.suntzu19,
            R.drawable.suntzu20, R.drawable.suntzu21, R.drawable.suntzu22, R.drawable.suntzu23, R.drawable.suntzu24, R.drawable.suntzu25, R.drawable.suntzu26, R.drawable.suntzu27, R.drawable.suntzu28, R.drawable.suntzu29, R.drawable.suntzu30, R.drawable.suntzu31, R.drawable.suntzu32, R.drawable.voltaire01, R.drawable.voltaire02, R.drawable.voltaire03, R.drawable.voltaire04, R.drawable.voltaire05, R.drawable.voltaire06, R.drawable.voltaire07, R.drawable.voltaire08, R.drawable.voltaire09, R.drawable.voltaire10, R.drawable.voltaire11, R.drawable.voltaire12, R.drawable.voltaire13, R.drawable.voltaire14, R.drawable.voltaire15};



    public int[] loadQuotes() {

        getAllImages();

        return imagesPt;

    }


    public int getQuoteImagePt() {

        //getAllImages();

        Random random = new Random();

        int indice = random.nextInt(imagesPt.length);

        return imagesPt[indice];
    }

    public void getAllImages(){

        Field[] ID_Fields = R.drawable.class.getFields();
        int[] resArray = new int[ID_Fields.length];

        for (int i =0; i<ID_Fields.length;i++) {

            try {

                resArray[i] = ID_Fields[i].getInt(null);

            } catch (Exception e) {

                e.printStackTrace();
            }

        }


    }



}
